### PR TITLE
Configure the clear completed button and the initialization button

### PR DESCRIPTION
**Pull request by DaveZag**
# Interactive todo list
### In this branch we:
- Configure the checkboxes to retain their state on load either checked or not.
- Configure the clear Completed button to delete all checked tasks.
- Configure Reinitialize button to delete everything from the list and the local storage.
Demo:
ezgif-5-f4a03082d6

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @DaveZag  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of GitHub Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] When I delete an item from the Todo List, It deleted everything from the local storage instead of deleting that particular item. Kindly fix this 👍🏻 
Screenshot 2022-10-01 at 5 07 00 PM

- [x] After deleting selected items, ids of todo items should be in sequence 
#### For Example: 
```
We have an array and we delete the second value i.e., 2 
so the remaining items are [1, 3, 4] with indexes 0, 1, 2 and not 0, 2, 3. 
Let me know if there's still any confusion 👍🏻 
[1, 2, 3, 4] 
```
_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DaveZag** [comment]
Hi @zainsadaqat  Thanks for the feedback.
I've implemented the required changes. Let me know If I pass them all.🙃

**Review by Qoosim — APPROVED** [review]
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @DaveZag, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

-  No linter errors. :heavy_check_mark: 
-  Code worked as expected. :heavy_check_mark: 
-   Good commit messages. :heavy_check_mark: 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DaveZag** [comment]
Hi @Qoosim , Thanks for the feedback.

**Pull request merged**
